import crypto from 'crypto';
import { ensureDbExists } from '@/lib/db';
import { pgGetActiveCustomerForSession, pgGetActiveStaffForSession } from '@/lib/postgres-session-auth';
import type { MerchantTier } from '@/types';

export const SESSION_COOKIE_NAME = 'etihad_admin_session';
export const CUSTOMER_SESSION_COOKIE_NAME = 'etihad_customer_session';
export const SESSION_DURATION_SECONDS = 7 * 24 * 60 * 60;
export const CUSTOMER_SESSION_DURATION_SECONDS = 30 * 24 * 60 * 60;
function getSessionSecret(): string { const envSecret = process.env.ADMIN_SESSION_SECRET; if (envSecret && envSecret.trim().length >= 16) return envSecret.trim(); if (process.env.NODE_ENV === 'production') throw new Error('SECURITY CONFIGURATION ERROR: ADMIN_SESSION_SECRET environment variable is missing or too short.'); return 'dev-local-test-secret-never-used-in-production'; }
export interface AuthenticatedAdmin { id: string; name: string; username: string; role: 'admin' | 'staff'; jobTitle?: string; permissions: string[]; isActive: boolean; }
export interface SessionPayload { userId: string; username: string; role: string; exp: number; }
export function signAdminSession(payload: SessionPayload): string { const data = Buffer.from(JSON.stringify(payload)).toString('base64url'); const sig = crypto.createHmac('sha256', getSessionSecret()).update(data).digest('base64url'); return `${data}.${sig}`; }
export function verifyAdminSessionToken(token: string): SessionPayload | null { if (!token || typeof token !== 'string') return null; const parts = token.split('.'); if (parts.length !== 2) return null; const [data, sig] = parts; const expectedSig = crypto.createHmac('sha256', getSessionSecret()).update(data).digest('base64url'); if (sig.length !== expectedSig.length || !crypto.timingSafeEqual(Buffer.from(sig), Buffer.from(expectedSig))) return null; try { const payload = JSON.parse(Buffer.from(data, 'base64url').toString('utf-8')) as SessionPayload; return payload.exp && payload.exp >= Math.floor(Date.now() / 1000) ? payload : null; } catch { return null; } }
export function getSessionFromRequest(request: Request): SessionPayload | null { const authHeader = request.headers.get('authorization') || ''; if (authHeader.startsWith('Bearer ')) { const payload = verifyAdminSessionToken(authHeader.substring(7).trim()); if (payload && (payload.role === 'admin' || payload.role === 'staff')) return payload; } const cookieHeader = request.headers.get('cookie') || ''; const match = cookieHeader.match(new RegExp(`(?:^|;\\s*)${SESSION_COOKIE_NAME}=([^;]+)`)); return match ? verifyAdminSessionToken(decodeURIComponent(match[1])) : null; }

// Legacy synchronous verifier retained temporarily for routes not migrated yet.
export function getAuthenticatedAdmin(request: Request): AuthenticatedAdmin | null { const session = getSessionFromRequest(request); if (!session) return null; const db = ensureDbExists(); const cleanU = (session.username || '').trim().toLowerCase(); const masterAuth = db.adminAuth || { username: 'admin', password: 'admin123' }; if (masterAuth.username.trim().toLowerCase() === cleanU) return { id: 'admin-master', name: 'المدير العام (Master Admin)', username: masterAuth.username, role: 'admin', jobTitle: 'مدير النظام الرئيسي 👑', permissions: ['*'], isActive: true }; const staff = (db.staff || []).find(s => (s.username || '').trim().toLowerCase() === cleanU || s.id === session.userId); if (!staff || !staff.isActive) return null; return { id: staff.id, name: staff.name, username: staff.username, role: 'staff', jobTitle: staff.jobTitle, permissions: staff.permissions || [], isActive: staff.isActive }; }

/** PostgreSQL-backed verifier for routes migrated to async authentication. */
export async function getAuthenticatedAdminPg(request: Request): Promise<AuthenticatedAdmin | null> { const session = getSessionFromRequest(request); if (!session) return null; const staff = await pgGetActiveStaffForSession({ userId: session.userId, username: session.username }); if (!staff) return null; const isMaster = session.role === 'admin'; return { id: staff.id, name: staff.name, username: staff.username, role: isMaster ? 'admin' : 'staff', jobTitle: staff.jobTitle, permissions: isMaster ? ['*'] : staff.permissions, isActive: staff.isActive }; }
export function hasPermission(admin: AuthenticatedAdmin | null, requiredPermission: string): boolean { if (!admin || !admin.isActive) return false; if (admin.role === 'admin') return true; const perms = admin.permissions || []; if (perms.includes('*') || perms.includes(requiredPermission)) return true; if (requiredPermission.startsWith('accounting:') && perms.includes('accounting')) return true; if (requiredPermission.startsWith('drivers:') && (perms.includes('drivers') || perms.includes('accounting'))) return true; if (requiredPermission.startsWith('vault:') && perms.includes('accounting')) return true; return false; }

export interface CustomerSessionPayload { userId: string; phone: string; email?: string; name?: string; role?: string; exp: number; }
export interface AuthenticatedCustomer { id: string; phone: string; email?: string; name: string; accountType?: string; role?: string; merchantStatus?: string; pricingTier?: string; merchantTier?: MerchantTier; isActive: boolean; }
export function signCustomerSession(payload: CustomerSessionPayload): string { const data = Buffer.from(JSON.stringify(payload)).toString('base64url'); const sig = crypto.createHmac('sha256', getSessionSecret()).update(data).digest('base64url'); return `${data}.${sig}`; }
export function verifyCustomerSessionToken(token: string): CustomerSessionPayload | null { if (!token || typeof token !== 'string') return null; const parts = token.split('.'); if (parts.length !== 2) return null; const [data, sig] = parts; const expectedSig = crypto.createHmac('sha256', getSessionSecret()).update(data).digest('base64url'); if (sig.length !== expectedSig.length || !crypto.timingSafeEqual(Buffer.from(sig), Buffer.from(expectedSig))) return null; try { const payload = JSON.parse(Buffer.from(data, 'base64url').toString('utf-8')) as CustomerSessionPayload; return payload.exp && payload.exp >= Math.floor(Date.now() / 1000) ? payload : null; } catch { return null; } }
function getCustomerSessionFromRequest(request: Request): CustomerSessionPayload | null { let token: string | null = null; const authHeader = request.headers.get('authorization') || ''; if (authHeader.startsWith('Bearer ')) token = authHeader.substring(7).trim(); if (!token) { const match = (request.headers.get('cookie') || '').match(new RegExp(`(?:^|;\\s*)${CUSTOMER_SESSION_COOKIE_NAME}=([^;]+)`)); if (match) token = decodeURIComponent(match[1]); } return token ? verifyCustomerSessionToken(token) : null; }
export function getAuthenticatedCustomer(request: Request): AuthenticatedCustomer | null { const payload = getCustomerSessionFromRequest(request); if (!payload?.userId) return null; const db = ensureDbExists(); const user = (db.users || []).find(u => u.id === payload.userId); if (!user || (user as any).isActive === false || (user as any).disabled === true || (user as any).status === 'disabled') return null; return { id: user.id, phone: user.phone, email: user.email, name: user.name, accountType: user.accountType || 'individual', role: user.role, merchantStatus: user.merchantStatus, pricingTier: user.pricingTier, merchantTier: user.merchantTier, isActive: (user as any).isActive !== false }; }
/** PostgreSQL-backed customer verifier for routes migrated to async authentication. */
export async function getAuthenticatedCustomerPg(request: Request): Promise<AuthenticatedCustomer | null> { const payload = getCustomerSessionFromRequest(request); if (!payload?.userId) return null; const user = await pgGetActiveCustomerForSession(payload.userId); if (!user) return null; return { id: user.id, phone: user.phone, email: payload.email, name: user.name, accountType: user.accountType, role: payload.role, merchantStatus: user.merchantStatus, pricingTier: user.pricingTier, merchantTier: user.merchantTier, isActive: true }; }

export interface OrderTokenPayload { orderId: string; orderNumber?: string; phone?: string; exp: number; }
export function signOrderAccessToken(payload: OrderTokenPayload): string { const data = Buffer.from(JSON.stringify(payload)).toString('base64url'); const sig = crypto.createHmac('sha256', getSessionSecret()).update(data).digest('base64url'); return `${data}.${sig}`; }
export function verifyOrderAccessToken(token: string, expectedOrderId?: string): OrderTokenPayload | null { if (!token || typeof token !== 'string') return null; const parts = token.split('.'); if (parts.length !== 2) return null; const [data, sig] = parts; const expectedSig = crypto.createHmac('sha256', getSessionSecret()).update(data).digest('base64url'); if (sig.length !== expectedSig.length || !crypto.timingSafeEqual(Buffer.from(sig), Buffer.from(expectedSig))) return null; try { const payload = JSON.parse(Buffer.from(data, 'base64url').toString('utf-8')) as OrderTokenPayload; if (!payload.exp || payload.exp < Math.floor(Date.now() / 1000) || (expectedOrderId && payload.orderId !== expectedOrderId)) return null; return payload; } catch { return null; } }
export function getOrderAccessTokenFromRequest(request: Request, orderId?: string): string | null { try { const token = new URL(request.url).searchParams.get('token'); if (token) return token; } catch {} const headerToken = request.headers.get('x-order-token'); if (headerToken) return headerToken; const authHeader = request.headers.get('authorization') || ''; if (authHeader.startsWith('Bearer ')) { const bearer = authHeader.substring(7).trim(); if (orderId && verifyOrderAccessToken(bearer, orderId)) return bearer; } const cookieHeader = request.headers.get('cookie') || ''; if (orderId) { const specificMatch = cookieHeader.match(new RegExp(`(?:^|;\\s*)etihad_order_token_${orderId}=([^;]+)`)); if (specificMatch) return decodeURIComponent(specificMatch[1]); } const generalMatch = cookieHeader.match(/(?:^|;\s*)etihad_order_token=([^;]+)/); return generalMatch ? decodeURIComponent(generalMatch[1]) : null; }
export function hashPassword(password: string): string { if (!password || typeof password !== 'string') throw new Error('كلمة المرور مطلوبة للتشفير'); const salt = crypto.randomBytes(16).toString('hex'); const derivedKey = crypto.scryptSync(password.trim(), salt, 64); return `scrypt:${salt}:${derivedKey.toString('hex')}`; }
export function verifyPassword(password: string, hash?: string | null): boolean { if (!password || !hash || typeof hash !== 'string') return false; const parts = hash.split(':'); if (parts.length !== 3 || parts[0] !== 'scrypt') return false; const [, salt, originalHex] = parts; try { const derivedHex = crypto.scryptSync(password.trim(), salt, 64).toString('hex'); return derivedHex.length === originalHex.length && crypto.timingSafeEqual(Buffer.from(derivedHex, 'hex'), Buffer.from(originalHex, 'hex')); } catch { return false; } }

export const DRIVER_SESSION_COOKIE_NAME = 'etihad_driver_session';
export const DRIVER_SESSION_DURATION_SECONDS = 30 * 24 * 60 * 60;
export interface DriverSessionPayload { driverId: string; authIdentityId?: string; phone: string; name: string; role: 'driver'; exp: number; }
export interface AuthenticatedDriver { id: string; authIdentityId: string; financialAccountId: string; name: string; phone: string; isActive: boolean; }
export function signDriverSession(payload: DriverSessionPayload): string { const data = Buffer.from(JSON.stringify(payload)).toString('base64url'); const sig = crypto.createHmac('sha256', getSessionSecret()).update(data).digest('base64url'); return `${data}.${sig}`; }
export function verifyDriverSessionToken(token: string): DriverSessionPayload | null { if (!token || typeof token !== 'string') return null; const parts = token.split('.'); if (parts.length !== 2) return null; const [data, sig] = parts; const expectedSig = crypto.createHmac('sha256', getSessionSecret()).update(data).digest('base64url'); if (sig.length !== expectedSig.length || !crypto.timingSafeEqual(Buffer.from(sig), Buffer.from(expectedSig))) return null; try { const payload = JSON.parse(Buffer.from(data, 'base64url').toString('utf-8')) as DriverSessionPayload; return payload.exp && payload.exp >= Math.floor(Date.now() / 1000) && payload.role === 'driver' ? payload : null; } catch { return null; } }
export function getDriverSessionFromRequest(request: Request): DriverSessionPayload | null { let token: string | null = null; const authHeader = request.headers.get('authorization') || ''; if (authHeader.startsWith('Bearer ')) token = authHeader.substring(7).trim(); if (!token) { const match = (request.headers.get('cookie') || '').match(new RegExp(`(?:^|;\\s*)${DRIVER_SESSION_COOKIE_NAME}=([^;]+)`)); if (match) token = decodeURIComponent(match[1]); } return token ? verifyDriverSessionToken(token) : null; }
export function getAuthenticatedDriver(request: Request): AuthenticatedDriver | null { const payload = getDriverSessionFromRequest(request); if (!payload) return null; const db = ensureDbExists(); const driver = (db.drivers || []).find((d: any) => d.id === payload.driverId || (payload.authIdentityId && (d as any).authIdentityId === payload.authIdentityId)); if (!driver || driver.isActive === false) return null; const legacyDriver = driver as any; return { id: driver.id, authIdentityId: legacyDriver.authIdentityId || payload.authIdentityId || '', financialAccountId: legacyDriver.financialAccountId || '', name: driver.name, phone: driver.phone, isActive: driver.isActive !== false }; }
