import { NextResponse } from 'next/server';
import { pgSavePushSubscription, pgGetPushAudienceStats } from '@/lib/postgres-push-notifications';
import { VAPID_PUBLIC_KEY } from '@/lib/pushService';
import { getAuthenticatedCustomerPg } from '@/lib/auth';
import type { AccountType } from '@/types';
export const dynamic = 'force-dynamic'; export const revalidate = 0;
const VALID_ACCOUNT_TYPES: readonly AccountType[] = ['individual', 'market', 'wholesale', 'merchant', 'supplier'];
type PushDeviceType = 'mobile' | 'desktop' | 'tablet'; const VALID_DEVICE_TYPES: readonly PushDeviceType[] = ['mobile', 'desktop', 'tablet'];
function parseAccountType(value: unknown): AccountType | 'visitor' { return typeof value === 'string' && VALID_ACCOUNT_TYPES.includes(value as AccountType) ? value as AccountType : 'visitor'; }
function parseDeviceType(value: unknown): PushDeviceType { if (typeof value !== 'string') return 'mobile'; const normalized = value.trim().toLowerCase(); return VALID_DEVICE_TYPES.includes(normalized as PushDeviceType) ? normalized as PushDeviceType : 'mobile'; }
export async function GET() { try { const stats = await pgGetPushAudienceStats(); return NextResponse.json({ success: true, vapidPublicKey: VAPID_PUBLIC_KEY, ...stats }); } catch (error) { console.error('GET /api/notifications/subscribe failed:', error); return NextResponse.json({ success: false, error: 'تعذر تحميل معلومات الإشعارات' }, { status: 500 }); } }
export async function POST(request: Request) { try { const body = await request.json(); const { subscription, deviceType } = body; if (!subscription || typeof subscription.endpoint !== 'string' || !subscription.endpoint.trim() || !subscription.keys || typeof subscription.keys.p256dh !== 'string' || !subscription.keys.p256dh.trim() || typeof subscription.keys.auth !== 'string' || !subscription.keys.auth.trim()) return NextResponse.json({ success: false, error: 'بيانات الاشتراك غير مكتملة' }, { status: 400 }); if (subscription.endpoint.length > 4096 || subscription.keys.p256dh.length > 1024 || subscription.keys.auth.length > 1024) return NextResponse.json({ success: false, error: 'بيانات الاشتراك غير صالحة' }, { status: 400 }); const customer = await getAuthenticatedCustomerPg(request); const saved = await pgSavePushSubscription({ endpoint: subscription.endpoint.trim(), keys: { p256dh: subscription.keys.p256dh.trim(), auth: subscription.keys.auth.trim() }, userId: customer?.id, userPhone: customer?.phone, userName: customer?.name, accountType: parseAccountType(customer?.accountType), deviceType: parseDeviceType(deviceType), userAgent: request.headers.get('user-agent') || undefined }); return NextResponse.json({ success: true, message: 'تم تفعيل واستلام إشعارات المتجر بنجاح 🔔', subscription: saved }); } catch (error) { console.error('POST /api/notifications/subscribe failed:', error); return NextResponse.json({ success: false, error: 'تعذر حفظ اشتراك الإشعارات' }, { status: 500 }); } }
