import { NextResponse } from 'next/server';
import { sendWebPushNotification } from '@/lib/pushService';
import { pgClearAllPushNotificationLogs, pgDeletePushNotificationLog, pgGetPushNotificationLogs } from '@/lib/postgres-push-notifications';
import { getAuthenticatedAdmin } from '@/lib/auth';
import type { NotificationTargetAudience } from '@/types';
export const dynamic = 'force-dynamic'; export const revalidate = 0;
const VALID_TARGET_AUDIENCES: readonly NotificationTargetAudience[] = ['all','wholesale','market','retail','registered_no_orders','inactive_30d','few_orders','active_vip'];
function parseTargetAudience(value: unknown): NotificationTargetAudience { return typeof value === 'string' && VALID_TARGET_AUDIENCES.includes(value as NotificationTargetAudience) ? value as NotificationTargetAudience : 'all'; }
function requireMasterAdmin(request: Request) { const admin = getAuthenticatedAdmin(request); if (!admin) return { admin: null, response: NextResponse.json({ success: false, error: 'غير مصرح لك بالوصول' }, { status: 401 }) }; if (admin.role !== 'admin') return { admin: null, response: NextResponse.json({ success: false, error: 'إدارة الإشعارات العامة محصورة بالمدير العام فقط' }, { status: 403 }) }; return { admin, response: null }; }
export async function GET(request: Request) { try { const auth = requireMasterAdmin(request); if (auth.response) return auth.response; return NextResponse.json({ success: true, logs: await pgGetPushNotificationLogs() }); } catch (error) { console.error('GET /api/notifications/send failed:', error); return NextResponse.json({ success: false, error: 'تعذر تحميل سجل الإشعارات' }, { status: 500 }); } }
export async function POST(request: Request) {
  try { const auth = requireMasterAdmin(request); if (auth.response) return auth.response; const body = await request.json(); const { title, message, body: bodyText, image, url, targetAudience, expiryHours } = body; const finalTitle = typeof title === 'string' ? title.trim() : ''; const finalBody = typeof (bodyText || message) === 'string' ? (bodyText || message).trim() : '';
    if (!finalTitle || !finalBody || finalTitle.length > 200 || finalBody.length > 4000) return NextResponse.json({ success: false, error: 'يرجى كتابة عنوان ونص إشعار صالحين' }, { status: 400 });
    const hours = typeof expiryHours === 'number' && Number.isFinite(expiryHours) ? Math.min(Math.max(expiryHours, 0), 168) : 0; const expiresAt = hours > 0 ? new Date(Date.now() + hours * 3600000).toISOString() : undefined;
    const result = await sendWebPushNotification({ title: finalTitle, body: finalBody, image: typeof image === 'string' && image.trim() ? image.trim() : undefined, url: typeof url === 'string' && url.trim() ? url.trim() : '/', targetAudience: parseTargetAudience(targetAudience), sentByStaffId: auth.admin!.id, expiryHours: hours, expiresAt });
    return NextResponse.json({ success: true, message: `تم إرسال التنبيه بنجاح إلى ${result.successCount} جهاز من أصل ${result.totalTargeted} 🚀`, result });
  } catch (error: any) { console.error('POST /api/notifications/send failed:', error); if (String(error?.message) === 'PUSH_NOT_CONFIGURED') return NextResponse.json({ success: false, error: 'خدمة الإشعارات غير مهيأة على السيرفر' }, { status: 503 }); return NextResponse.json({ success: false, error: 'تعذر إرسال الإشعار' }, { status: 500 }); }
}
export async function DELETE(request: Request) { try { const auth = requireMasterAdmin(request); if (auth.response) return auth.response; const { searchParams } = new URL(request.url); const id = searchParams.get('id'); if (searchParams.get('clearAll') === 'true') { await pgClearAllPushNotificationLogs(); return NextResponse.json({ success: true, message: 'تم مسح سجل الإشعارات بالكامل بنجاح' }); } if (!id) return NextResponse.json({ success: false, error: 'معرف الإشعار مطلوب للحذف' }, { status: 400 }); await pgDeletePushNotificationLog(id); return NextResponse.json({ success: true, message: 'تم حذف الإشعار بنجاح' }); } catch (error) { console.error('DELETE /api/notifications/send failed:', error); return NextResponse.json({ success: false, error: 'تعذر حذف سجل الإشعار' }, { status: 500 }); } }
